
ORG 0000H
    SJMP 0030H         ; Skipping to Main Program

ORG 0500H
    MYCOM: DB 38H,01H,0EH,06H,80H,0
    FIRST: DB "PROJECT DEMO",0
    SECOND: DB "CONNECTING  TO",0
    THIRD: DB "GPS",0
    FOURTH: DB "CONNECTION",0
    FIFTH: DB "SUCCESFULL",0
    LAT: DB "LAT: ",0
    LON: DB "LON: ",0

; Command Subroutine for LCD
COMSUB:
    CLR P2.0
    CLR P2.2
    SETB P2.1
    MOV P1, A
    CLR P2.1
    ACALL DELAY
    RET

; Data Subroutine for LCD
DATASUB:
    SETB P2.0
    CLR P2.2
    SETB P2.1
    MOV P1, A
    CLR P2.1
    ACALL DELAY
    RET

; Delay Subroutine
DELAY:
    MOV R3, #0DDH
L1: MOV R0, #0FFH
HERED: DJNZ R0, HERED
    DJNZ R3, L1
    RET

; Print Subroutine
PRINT:
    NOP
PRINTLOOP:
    CLR A
    MOVC A, @A+DPTR
    JZ EXITPRINT
    ACALL DATASUB
    INC DPTR
    SJMP PRINTLOOP
EXITPRINT:
    NOP
    RET

ORG 0030H
    MOV TMOD, #20H
    MOV TH1, #-03DH
    MOV SCON, #50H

    MOV DPTR, #MYCOM
COMLOOP:
    CLR A
    MOVC A, @A+DPTR
    JZ EXITCOM
    ACALL COMSUB
    INC DPTR
    SJMP COMLOOP

EXITCOM:
    MOV A, #82H
    ACALL COMSUB
    MOV DPTR, #FIRST
    ACALL PRINT
    ACALL DELAY
    MOV A, #01H
    ACALL COMSUB
    MOV A, #82H
    ACALL COMSUB
    MOV DPTR, #SECOND
    ACALL PRINT
    MOV A, #0C7H
    ACALL COMSUB
    MOV DPTR, #THIRD
    ACALL PRINT

MAINLOOP:
AGAIN:
    SETB TR1
    CLR RI
HERE:
    JNB RI, HERE
    MOV A, SBUF
    CLR TR1
    CJNE A, #'$', AGAIN

    MOV R0, #50H
    MOV R5, #50D
AGAIN1:
    SETB TR1
    CLR RI
HERE1:
    JNB RI, HERE1
    MOV A, SBUF
    MOV @R0, A
    INC R0
    CLR TR1
    DJNZ R5, AGAIN1

    MOV R0, #50H
    CJNE @R0, #'G', AGAIN
    INC R0
    CJNE @R0, #'N', AGAIN
    INC R0
    CJNE @R0, #'G', AGAIN
    INC R0
    CJNE @R0, #'G', AGAIN
    INC R0
    CJNE @R0, #'A', AGAIN

    CJNE R7, #01H, NORMAL
    SJMP SKIP

NORMAL:
    MOV A, #01H
    ACALL COMSUB
    MOV A, #83H
    ACALL COMSUB
    MOV DPTR, #FOURTH
    ACALL PRINT
    MOV A, #0C3H
    ACALL COMSUB
    MOV DPTR, #FIFTH
    ACALL PRINT

SKIP:
    ACALL DELAY
    MOV A, #01H
    ACALL COMSUB

; LATITUDE DISPLAY
LATITUDE:
    MOV A, #80H
    ACALL COMSUB
    MOV DPTR, #LAT
LALOOP:
    CLR A
    MOVC A, @A+DPTR
    JZ LATVALUE
    ACALL DATASUB
    INC DPTR
    SJMP LALOOP

LATVALUE:
    MOV R1, #61H
LATNUM:
    CLR A
    MOV A, @R1
    ACALL DATASUB
    INC R1
    CJNE R1, #6AH, LATNUM

    MOV A, #0C0H
    ACALL COMSUB

; LONGITUDE DISPLAY
LONGITUDE:
    MOV DPTR, #LON
LONLOOP:
    CLR A
    MOVC A, @A+DPTR
    JZ LONVALUE
    ACALL DATASUB
    INC DPTR
    SJMP LONLOOP

LONVALUE:
    MOV R1, #6EH
LONNUM:
    CLR A
    MOV A, @R1
    ACALL DATASUB
    INC R1
    CJNE R1, #78H, LONNUM

    CJNE R7, #01H, FIRSTLOOP
    SJMP NEXTLOOPS

FIRSTLOOP:
    INC R7

NEXTLOOPS:
    ACALL DELAY
    MOV A, #01H
    ACALL COMSUB
    AJMP MAINLOOP

END
